### ISSUE TITLE
To-Do list and feature ideas

### ISSUE THREAD

**Issue by mdfwn** [mdfwn/Dota2ProTracker#4]
- [ ] push new UI
- [ ] rewrite the error and exception handling
- [ ] look into how we could use the database/match_logger.py to make the new sidebar faster (i.e. less API calls)

Low priority:

- [ ] clean up directory structure and imports
- [ ] also look for pro players in league matches (e.g. FPL)
- [ ] merge with tournament matches (dotabuff, opendota)?
